stages:
- name: Deploy mysql
  steps:
  - applyYamlConfig:
      path: ./deployment/db/db1-mysql.yaml
timeout: 60
notification: {}

stages:
- name: Deploy phpmyadmin
  steps:
  - applyYamlConfig:
      path: ./deployment/phpmyadminadmin-mysql.yaml
timeout: 60
notification: {}

stages:
- name: Deploy wordpress
  steps:
  - applyYamlConfig:
      path: ./deployment/wordpress/wp-1.yaml
timeout: 60
notification: {}