stages:
- name: Build and Publish Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/wordpress/Dockerfile
      buildContext: .
      tag: wp:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34949
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./kubernetes/deployment.yaml
timeout: 60
notification: {}
