stages:
- name: Deploy db
  steps:
  - applyYamlConfig:
      path: ./deployment/db/db-mysql.yaml
- name: Deploy wordpress
  steps:
  - applyYamlConfig:
      path: ./deployment/wordpress/wp.yaml
timeout: 60
notification: {}
