version: "3.6"

services:

  db:
    build: ./docker/db
    restart: always
    volumes: 
      - ./data/db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  wp:
    build: ./docker/wordpress
    restart: always
    depends_on: 
      - db
    ports: 
      - "80:80"
    volumes: 
      - ./app:/var/www/html
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    build: ./docker/phpmyadmin
    restart: always
    depends_on:
      - db
    ports: 
      - "3000:80"
    environment: 
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    
volumes:
  db_data: {}